version: '3'

services:

  app:
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    container_name: front_app
